#!/bin/bash

set -e

UPDATE_FILE=update.tar.xz

if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]
then
    echo "Usage $0 DEB [DEB [..]]"
    exit 1
fi

for f in "$@"
do
    if [ "${f: -4}" != ".deb" ]
    then
        echo "Warning: '$f' doesn't look like a debian package"
    fi
done

tar --create --xz --transform 's_.*/__g' --file $UPDATE_FILE "$@"

DUPLICATES=$(tar --list --file $UPDATE_FILE | sort | uniq --repeated)

if [ ! -z "$DUPLICATES" ]
then
    echo "Warning: update contains duplicate files:"
    echo "$DUPLICATES"
fi
