#!/bin/bash

if [ -z "$1" ]
then
    echo "Usage $0 DEB [DEB [..]]"
    exit 1
fi

for f in "$@"
do
    if [ "${f: -4}" != ".deb" ]
    then
        echo "Warning: '$f' doesn't look like a debian package"
    fi
done

exec tar --create --xz --file update.tar.xz "$@"
