version: 2
jobs:
  build:
    docker:
      # While we're actually running on stretch (with Python 3.5.3), this is the
      # closest matching docker image available in CircleCI. The stretch images
      # all have Python 3.6, which has some syntactic changes.
      - image: python:3.5.4
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: venv/bin/pip install -r script/linting/requirements.txt
      - run: venv/bin/pip install -r script/typing/requirements.txt
      - run:
          command: script/linting/lint
          environment:
            FLAKE8: venv/bin/flake8
      - run:
          command: script/typing/check
          environment:
            MYPY: venv/bin/mypy
