name: Linting & type checking

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLAKE8: venv/bin/flake8
      MYPY: venv/bin/mypy
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Set up virtualenv
      run: python -m venv venv
    - name: Install dependencies
      run: |
        venv/bin/pip install -r script/linting/requirements.txt
        venv/bin/pip install -r script/typing/requirements.txt
    - name: Linting
      run: script/linting/lint
    - name: Type checking
      run: script/typing/check
